{{- if .Values.authScripts.enabled }}
# Test change
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "argocd-image-updater.labels" . | nindent 4 }}
  name: argocd-image-updater-authscripts
data:
  {{- toYaml .Values.authScripts.scripts | nindent 2}}
{{- end }}
